# Generated by Django 3.1 on 2020-10-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RssFeed', '0002_post_group_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='field_name',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
