# Generated by Django 3.1 on 2020-10-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RssFeed', '0003_post_field_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='field_name',
            new_name='img_field',
        ),
    ]
